arXiv:
  - query: "transformer"
    max_results: 10
    lifecycle_days: 180 # 生命周期，0 为每次最新，-1 为不丢弃任何条目
  - query: '("llm" OR "large language model" OR "large language models")'
    max_results: 30
    lifecycle_days: 180


news_source:
  lifecycle_days: 0
  sources: # 不想使用的源可以注释掉
    - id: v2ex-share
      name: V2EX-最新分享
    - id: zhihu
      name: 知乎
    - id: weibo
      name: 微博-实时热搜
    - id: zaobao
      name: 联合早报
    # - id: coolapk
    #   name: 酷安-今日最热
    - id: mktnews-flash
      name: MKTNews-快讯
    - id: wallstreetcn-quick
      name: 华尔街见闻-快讯
    - id: wallstreetcn-news
      name: 华尔街见闻-最新
    - id: wallstreetcn-hot
      name: 华尔街见闻-最热
    - id: 36kr-quick
      name: 36氪-快讯
    - id: 36kr-renqi
      name: 36氪-人气榜
    - id: douyin
      name: 抖音
    - id: hupu
      name: 虎扑-主干道热帖
    # - id: tieba
    #   name: 百度贴吧-热议
    - id: toutiao
      name: 今日头条
    - id: ithome
      name: IT之家
    - id: thepaper
      name: 澎湃新闻-热榜
    - id: sputniknewscn
      name: 卫星通讯社
    - id: cankaoxiaoxi
      name: 参考消息
    # - id: pcbeta-windows11
    #   name: 远景论坛-Win11
    - id: cls-telegraph
      name: 财联社-电报
    - id: cls-depth
      name: 财联社-深度
    - id: cls-hot
      name: 财联社-热门
    - id: xueqiu-hotstock
      name: 雪球-热门股票
    - id: gelonghui
      name: 格隆汇-事件
    - id: fastbull-express
      name: 法布财经-快讯
    - id: fastbull-news
      name: 法布财经-头条
    - id: solidot
      name: Solidot
    - id: hackernews
      name: Hacker News
    - id: producthunt
      name: Product Hunt
    - id: github-trending-today
      name: Github-Today
    - id: bilibili
      name: 哔哩哔哩
    # - id: kuaishou
    #   name: 快手
    - id: kaopu
      name: 靠谱新闻
    - id: jin10
      name: 金十数据
    - id: baidu
      name: 百度热搜
    - id: nowcoder
      name: 牛客
    - id: sspai
      name: 少数派
    - id: juejin
      name: 稀土掘金
    - id: ifeng
      name: 凤凰网-热点资讯
    - id: chongbuluo-latest
      name: 虫部落-最新
    - id: chongbuluo-hot
      name: 虫部落-最热
    # - id: douban
    #   name: 豆瓣-热门电影
    # - id: steam
    #   name: Steam-在线人数
    - id: tencent-hot
      name: 腾讯新闻-综合早报
    - id: freebuf
      name: Freebuf-网络安全
    # - id: qqvideo-tv-hotsearch
    #   name: 腾讯视频-热搜榜
    # - id: iqiyi-hot-ranklist
    #   name: 爱奇艺-热播榜

rss:
  - id: "hacker-news"
    name: "Hacker News"
    url: "https://hnrss.org/frontpage"
    lifecycle_days: 2 # default: 7

  - id: "ruanyifeng"
    name: "阮一峰的网络日志"
    url: "http://www.ruanyifeng.com/blog/atom.xml"
    lifecycle_days: 7

  - id: "yahoo-finance"
    name: "雅虎财经"
    url: "https://finance.yahoo.com/news/rssindex"
    lifecycle_days: 1


    # 自定义源示例
    # - id: "custom-feed"
    #   name: "自定义源"
    #   url: "https://example.com/feed.xml"
    #   lifecycle_days: 0               # 示例：禁用过滤，推送所有文章